import React from 'react';
import { Book, Crosshair, Lightbulb, Award, Layers, BarChart2 } from 'lucide-react'; // Import Lucide icons

const Manual = () => {
    return (
        <div className="max-w-5xl mx-auto fade-in glass-panel rounded-xl shadow-2xl overflow-hidden my-8 flex flex-col h-[85vh]">
            <div className="bg-slate-950 px-8 py-6 border-b border-slate-800 flex justify-between items-center sticky top-0 z-10">
                <h2 className="text-2xl font-bold text-white flex items-center gap-2">
                    <Book className="w-6 h-6 text-indigo-500" /> Operator Manual
                </h2>
                {/* Back button, can be a Link to / or use history.back() */}
                 <button onClick={() => window.history.back()} className="text-slate-500 hover:text-white font-bold px-4 py-2 hover:bg-slate-800 rounded transition-colors">&times; CLOSE</button>
            </div>

            <div className="p-8 space-y-12 overflow-y-auto text-slate-300 flex-grow">
                {/* Overview */}
                <section>
                    <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                        <Crosshair className="w-5 h-5 text-indigo-400" /> Mission Objectives
                    </h3>
                    <div className="bg-slate-800/50 p-6 rounded-xl border border-slate-700 text-sm leading-relaxed">
                        <p className="mb-4"><strong>Primary Goal:</strong> You play as the CEO of a digital marketing agency. Your goal is to scale your initial <strong>$100</strong> capital into a corporate empire. Climb the <strong>10 Tiers</strong> of the operator ladder.</p>
                        <p className="mb-4"><strong>The Loop:</strong></p>
                        <ul className="space-y-2 list-disc pl-5 marker:text-indigo-500">
                            <li><strong>Analyze:</strong> Review daily Prospects (3-5 randomized clients). Assess their "Taste" and contract length.</li>
                            <li><strong>Pitch:</strong> Select the right buzzword to sign clients to contracts.</li>
                            <li><strong>Simulate:</strong> Start the "Work Day" to let your active clients generate posts and views.</li>
                            <li><strong>Monetize:</strong> Earn money from views generated by client posts.</li>
                        </ul>
                    </div>
                </section>

                {/* Tips & Suggestions - Adapted */}
                <section>
                    <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                        <Lightbulb className="w-5 h-5 text-yellow-400" /> Strategic Advice
                    </h3>
                    <div className="bg-slate-800/50 p-6 rounded-xl border border-slate-700 text-sm space-y-4">
                        <p><strong className="text-indigo-400">1. Leverage Debt Wisely:</strong> Taking loans can boost your immediate capital for various needs. But beware of compound interest—always check the total repayment before signing, and manage your liquidity.</p>
                        <p><strong className="text-indigo-400">2. Volume is King:</strong> Due to the view cap per post ($0.50 per 100 views), your success depends on having a full roster of active clients. More clients mean more posts, more views, and more revenue.</p>
                        <p><strong className="text-indigo-400">3. Watch the Churn:</strong> Clients have temporary contracts. Keep an eye on "days left" and aggressively pitch new prospects to replace expiring contracts to maintain a steady revenue stream.</p>
                    </div>
                </section>

                {/* Leveling System - Adapted */}
                <section>
                    <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                        <Award className="w-5 h-5 text-indigo-400" /> Career Progression
                    </h3>
                    <div className="bg-slate-800/50 p-6 rounded-xl border border-slate-700 text-sm">
                        <p className="mb-4">Operators gain <strong>XP</strong> for every completed transaction, signed client, and achieving post view caps. Profitable actions yield bonus XP.</p>
                        <div className="grid grid-cols-2 md:grid-cols-5 gap-2 text-xs font-mono text-slate-400 text-center">
                            <span className="bg-slate-900 p-2 rounded border border-slate-800">1. Intern</span>
                            <span className="bg-slate-900 p-2 rounded border border-slate-800">2. Analyst</span>
                            <span className="bg-slate-900 p-2 rounded border border-slate-800">3. Associate</span>
                            <span className="bg-slate-900 p-2 rounded border border-slate-800">4. Trader</span>
                            <span className="bg-slate-900 p-2 rounded border border-slate-800">5. Broker</span>
                            <span className="bg-slate-900 p-2 rounded border border-slate-800">6. Manager</span>
                            <span className="bg-slate-900 p-2 rounded border border-slate-800">7. Director</span>
                            <span className="bg-slate-900 p-2 rounded border border-slate-800">8. VP</span>
                            <span className="bg-slate-900 p-2 rounded border border-slate-800">9. Executive</span>
                            <span className="bg-slate-900 p-2 rounded border border-slate-800 text-yellow-500 font-bold">10. Chairman</span>
                        </div>
                        <p className="mt-4 text-xs text-slate-500">*Each Rank requires 1000 XP.</p>
                    </div>
                </section>

                {/* Client Classification (Adapted from Rarity System) */}
                <section>
                    <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                        <Layers className="w-5 h-5 text-indigo-400" /> Client Archetypes
                    </h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                        <div className="p-4 border border-slate-700 rounded-lg bg-slate-800/50 flex gap-4">
                            <div className="text-slate-400"><Box className="w-8 h-8" /></div>
                            <div>
                                <span className="text-xs font-bold bg-slate-700 text-slate-300 px-2 py-1 rounded uppercase">Tech Startup</span>
                                <p className="text-xs mt-2 text-slate-400">Disruptive taste. Focus on Scalable, AI-Driven solutions.</p>
                            </div>
                        </div>
                        <div className="p-4 border border-blue-900/50 rounded-lg bg-blue-900/10 flex gap-4">
                            <div className="text-blue-400"><Zap className="w-8 h-8" /></div>
                            <div>
                                <span className="text-xs font-bold bg-blue-900/50 text-blue-300 px-2 py-1 rounded uppercase">Bakery</span>
                                <p className="text-xs mt-2 text-slate-400">Homey taste. Values Warm, Authentic, Family appeal.</p>
                            </div>
                        </div>
                        <div className="p-4 border border-purple-900/50 rounded-lg bg-purple-900/10 flex gap-4">
                            <div className="text-purple-400"><Star className="w-8 h-8" /></div>
                            <div>
                                <span className="text-xs font-bold bg-purple-900/50 text-purple-300 px-2 py-1 rounded uppercase">Gym Brand</span>
                                <p className="text-xs mt-2 text-slate-400">Hardcore taste. Emphasizes Grind, Power, Sweat.</p>
                            </div>
                        </div>
                        <div className="p-4 border border-yellow-900/50 rounded-lg bg-yellow-900/10 flex gap-4">
                            <div className="text-yellow-400"><Crown className="w-8 h-8" /></div>
                            <div>
                                <span className="text-xs font-bold bg-yellow-900/50 text-yellow-300 px-2 py-1 rounded uppercase">Luxury Watch</span>
                                <p className="text-xs mt-2 text-slate-400">Elegant taste. Focuses on Timeless, Classy, Prestige.</p>
                            </div>
                        </div>
                    </div>
                </section>

                {/* Market Dynamics - Adapted */}
                <section>
                    <h3 className="text-xl font-bold text-white mb-4 flex items-center gap-2">
                        <BarChart2 className="w-5 h-5 text-indigo-400" /> Agency Dynamics
                    </h3>
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="bg-slate-800/50 p-4 rounded-xl border border-slate-700">
                            <h4 className="font-bold text-white text-sm mb-2">Sim Speed Controls</h4>
                            <p className="text-xs text-slate-400">
                                Control the speed of the "Work Day" simulation (1x, 2x, 4x) or instantly skip to the end of the day.
                            </p>
                        </div>
                        <div className="bg-slate-800/50 p-4 rounded-xl border border-slate-700">
                            <h4 className="font-bold text-white text-sm mb-2">Rerolling Prospects</h4>
                            <p className="text-xs text-slate-400">
                                If current prospects aren't suitable, you can reroll to generate a fresh batch. Use strategically!
                            </p>
                        </div>
                    </div>
                </section>
            </div>
        </div>
    );
};

export default Manual;